singleuser:
  image:
    # Get the latest image tag at:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook/Dockerfile
    name: jupyter/datascience-notebook
    tag: 177037d09156
  defaultUrl: "/lab"

hub:
  config:
    Authenticator:
      admin_users:
        - netdb-admin
      allowed_users:
        - netdb
    JupyterHub:
      authenticator_class: ldapauthenticator.LDAPAuthenticator
    LDAPAuthenticator:
      use_ssl: false
      server_address: 172.17.0.7
      bind_dn_template:
        - cn={username},cn=dev,ou=research,ou=internal,dc=example,dc=org
        - cn={username},cn=admin,ou=research,ou=internal,dc=example,dc=org
